{
    "events": [
        {
            "json": {
                "log_id": "90020211103030609732115389415260839021644201259064885298",
                "data": {
                    "date": "2021-11-03T03:06:05.696Z",
                    "type": "f",
                    "description": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                    "connection_id": "",
                    "ip": "81.2.69.143",
                    "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0",
                    "details": {
                        "body": {},
                        "qs": {
                            "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                            "redirect_uri": "http://localhost:3000/callback",
                            "response_type": "code",
                            "scope": "openid profile",
                            "state": "Vz6G2zZf95/FCOQALrpvd4bS6jx5xvRos2pVldFAiw4="
                        },
                        "error": {
                            "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                            "oauthError": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs. Please go to 'https://manage.auth0.com/#/applications/aI61p8I8aFjmYRliLWgvM9ev97kCCNDB/settings' and make sure you are sending the same callback url from your application.",
                            "payload": {
                                "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                                "code": "unauthorized_client",
                                "status": 403,
                                "name": "CallbackMismatchError",
                                "authorized": [],
                                "attempt": "http://localhost:3000/callback",
                                "client": {
                                    "clientID": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB"
                                }
                            },
                            "type": "callback-url-mismatch"
                        }
                    },
                    "hostname": "dev-yoj8axza.au.auth0.com",
                    "log_id": "90020211103030609732115389415260839021644201259064885298"
                }
            }
        },
        {
            "json": {
                "log_id": "90020211103030609732115389415262047947463815888239591474",
                "data": {
                    "date": "2021-11-03T03:06:05.699Z",
                    "type": "f",
                    "description": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                    "connection_id": "",
                    "ip": "81.2.69.143",
                    "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0",
                    "details": {
                        "body": {},
                        "qs": {
                            "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                            "redirect_uri": "http://localhost:3000/callback",
                            "response_type": "code",
                            "scope": "openid profile",
                            "state": "Vz6G2zZf95/FCOQALrpvd4bS6jx5xvRos2pVldFAiw4="
                        },
                        "error": {
                            "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                            "oauthError": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs. Please go to 'https://manage.auth0.com/#/applications/aI61p8I8aFjmYRliLWgvM9ev97kCCNDB/settings' and make sure you are sending the same callback url from your application.",
                            "payload": {
                                "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                                "code": "unauthorized_client",
                                "status": 403,
                                "name": "CallbackMismatchError",
                                "authorized": [],
                                "attempt": "http://localhost:3000/callback",
                                "client": {
                                    "clientID": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB"
                                },
                                "log_url": "https://manage.auth0.com/#/logs/"
                            },
                            "type": "callback-url-mismatch"
                        }
                    },
                    "hostname": "dev-yoj8axza.au.auth0.com",
                    "log_id": "90020211103030609732115389415262047947463815888239591474"
                }
            }
        },
        {
            "json": {
                "log_id": "90020211104002953320334544994860291215054924285237788770",
                "data": {
                    "date": "2021-11-04T00:29:50.035Z",
                    "type": "f",
                    "description": "the connection is not enabled",
                    "connection": "NewDB",
                    "connection_id": "con_H5LL8aMFnXVZ2TS8",
                    "client_id": "360yuN1BXP4u3tBChK5VOgekgGJ7CwLL",
                    "client_name": "All Applications",
                    "ip": "81.2.69.143",
                    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
                    "details": {
                        "body": {},
                        "qs": {
                            "client_id": "360yuN1BXP4u3tBChK5VOgekgGJ7CwLL",
                            "response_type": "code",
                            "connection": "NewDB",
                            "prompt": "login",
                            "scope": "openid profile",
                            "redirect_uri": "https://manage.auth0.com/tester/callback?connection=NewDB"
                        },
                        "connection": "NewDB",
                        "error": {
                            "message": "the connection is not enabled",
                            "oauthError": "invalid_request",
                            "type": "request-error"
                        },
                        "session_id": "Z_IDr9JX5VzO1l-2IEk6bSXWP3mu4wMP",
                        "riskAssessment": null
                    },
                    "hostname": "dev-yoj8axza.au.auth0.com",
                    "audience": "https://dev-yoj8axza.au.auth0.com/userinfo",
                    "scope": [
                        "openid",
                        "profile"
                    ],
                    "log_id": "90020211104002953320334544994860291215054924285237788770"
                }
            }
        },
        {
            "json": {
                "log_id": "90020211103030725428115389447533113776256732300526485554",
                "data": {
                    "date": "2021-11-03T03:07:24.384Z",
                    "type": "fu",
                    "description": "Wrong email or password.",
                    "connection": "Username-Password-Authentication",
                    "connection_id": "con_1a5wCUmAs6VOU17n",
                    "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                    "client_name": "Default App",
                    "ip": "81.2.69.143",
                    "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0",
                    "details": {
                        "error": {
                            "message": "Wrong email or password."
                        }
                    },
                    "user_id": "",
                    "user_name": "neo@gmail.com",
                    "strategy": "auth0",
                    "strategy_type": "database",
                    "log_id": "90020211103030725428115389447533113776256732300526485554"
                }
            }
        },
        {
            "json": {
                "log_id": "90020211103082515482106767167326018758436529088273317970",
                "data": {
                    "date": "2021-11-03T08:25:14.466Z",
                    "type": "fp",
                    "description": "Wrong email or password.",
                    "connection": "Username-Password-Authentication",
                    "connection_id": "con_1a5wCUmAs6VOU17n",
                    "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                    "client_name": "Default App",
                    "ip": "81.2.69.143",
                    "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36",
                    "details": {
                        "error": {
                            "message": "Wrong email or password."
                        }
                    },
                    "user_id": "auth0|61823277a44a21007221a59a",
                    "user_name": "new@test.com",
                    "strategy": "auth0",
                    "strategy_type": "database",
                    "log_id": "90020211103082515482106767167326018758436529088273317970"
                }
            }
        }
    ]
}