{
    "expected": [
        {
            "@timestamp": "2021-11-03T03:06:05.696Z",
            "ecs": {
                "version": "1.12.0"
            },
            "auth0": {
                "logs": {
                    "data": {
                        "date": "2021-11-03T03:06:05.696Z",
                        "log_id": "90020211103030609732115389415260839021644201259064885298",
                        "hostname": "dev-yoj8axza.au.auth0.com",
                        "ip": "114.76.60.57",
                        "description": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                        "details": {
                            "error": {
                                "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                                "type": "callback-url-mismatch",
                                "payload": {
                                    "name": "CallbackMismatchError",
                                    "client": {
                                        "clientID": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB"
                                    },
                                    "code": "unauthorized_client",
                                    "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                                    "attempt": "http://localhost:3000/callback",
                                    "status": 403
                                },
                                "oauthError": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs. Please go to 'https://manage.auth0.com/#/applications/aI61p8I8aFjmYRliLWgvM9ev97kCCNDB/settings' and make sure you are sending the same callback url from your application."
                            },
                            "qs": {
                                "response_type": "code",
                                "redirect_uri": "http://localhost:3000/callback",
                                "state": "Vz6G2zZf95/FCOQALrpvd4bS6jx5xvRos2pVldFAiw4=",
                                "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                                "scope": "openid profile"
                            }
                        },
                        "type": "Failed login",
                        "classification": "Login - Failure",
                        "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
                    },
                    "log_id": "90020211103030609732115389415260839021644201259064885298"
                }
            },
            "log": {
                "level": "error"
            },
            "event": {
                "action": "failed-login",
                "category": [
                    "authentication"
                ],
                "type": [
                    "info"
                ],
                "kind": "event",
                "outcome": "failure"
            }
        },
        {
            "@timestamp": "2021-11-03T03:06:05.699Z",
            "ecs": {
                "version": "1.12.0"
            },
            "auth0": {
                "logs": {
                    "data": {
                        "date": "2021-11-03T03:06:05.699Z",
                        "log_id": "90020211103030609732115389415262047947463815888239591474",
                        "hostname": "dev-yoj8axza.au.auth0.com",
                        "ip": "114.76.60.57",
                        "description": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                        "details": {
                            "error": {
                                "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                                "type": "callback-url-mismatch",
                                "payload": {
                                    "code": "unauthorized_client",
                                    "log_url": "https://manage.auth0.com/#/logs/",
                                    "name": "CallbackMismatchError",
                                    "client": {
                                        "clientID": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB"
                                    },
                                    "message": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs",
                                    "attempt": "http://localhost:3000/callback",
                                    "status": 403
                                },
                                "oauthError": "Callback URL mismatch. http://localhost:3000/callback is not in the list of allowed callback URLs. Please go to 'https://manage.auth0.com/#/applications/aI61p8I8aFjmYRliLWgvM9ev97kCCNDB/settings' and make sure you are sending the same callback url from your application."
                            },
                            "qs": {
                                "response_type": "code",
                                "redirect_uri": "http://localhost:3000/callback",
                                "state": "Vz6G2zZf95/FCOQALrpvd4bS6jx5xvRos2pVldFAiw4=",
                                "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                                "scope": "openid profile"
                            }
                        },
                        "type": "Failed login",
                        "classification": "Login - Failure",
                        "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
                    },
                    "log_id": "90020211103030609732115389415262047947463815888239591474"
                }
            },
            "log": {
                "level": "error"
            },
            "event": {
                "action": "failed-login",
                "category": [
                    "authentication"
                ],
                "type": [
                    "info"
                ],
                "kind": "event",
                "outcome": "failure"
            }
        },
        {
            "@timestamp": "2021-11-04T00:29:50.035Z",
            "ecs": {
                "version": "1.12.0"
            },
            "auth0": {
                "logs": {
                    "data": {
                        "date": "2021-11-04T00:29:50.035Z",
                        "log_id": "90020211104002953320334544994860291215054924285237788770",
                        "audience": "https://dev-yoj8axza.au.auth0.com/userinfo",
                        "ip": "114.76.60.57",
                        "description": "the connection is not enabled",
                        "type": "Failed login",
                        "classification": "Login - Failure",
                        "client_id": "360yuN1BXP4u3tBChK5VOgekgGJ7CwLL",
                        "hostname": "dev-yoj8axza.au.auth0.com",
                        "connection_id": "con_H5LL8aMFnXVZ2TS8",
                        "scope": [
                            "openid",
                            "profile"
                        ],
                        "connection": "NewDB",
                        "details": {
                            "session_id": "Z_IDr9JX5VzO1l-2IEk6bSXWP3mu4wMP",
                            "qs": {
                                "response_type": "code",
                                "connection": "NewDB",
                                "redirect_uri": "https://manage.auth0.com/tester/callback?connection=NewDB",
                                "prompt": "login",
                                "client_id": "360yuN1BXP4u3tBChK5VOgekgGJ7CwLL",
                                "scope": "openid profile"
                            },
                            "connection": "NewDB",
                            "error": {
                                "message": "the connection is not enabled",
                                "type": "request-error",
                                "oauthError": "invalid_request"
                            }
                        },
                        "client_name": "All Applications",
                        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
                    },
                    "log_id": "90020211104002953320334544994860291215054924285237788770"
                }
            },
            "log": {
                "level": "error"
            },
            "event": {
                "action": "failed-login",
                "category": [
                    "authentication"
                ],
                "type": [
                    "info"
                ],
                "kind": "event",
                "outcome": "failure"
            }
        },
        {
            "@timestamp": "2021-11-03T03:07:24.384Z",
            "ecs": {
                "version": "1.12.0"
            },
            "auth0": {
                "logs": {
                    "data": {
                        "date": "2021-11-03T03:07:24.384Z",
                        "log_id": "90020211103030725428115389447533113776256732300526485554",
                        "user_name": "neo@gmail.com",
                        "ip": "114.76.60.57",
                        "description": "Wrong email or password.",
                        "strategy_type": "database",
                        "type": "Invalid email or username",
                        "classification": "Login - Failure",
                        "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                        "connection_id": "con_1a5wCUmAs6VOU17n",
                        "connection": "Username-Password-Authentication",
                        "details": {
                            "error": {
                                "message": "Wrong email or password."
                            }
                        },
                        "strategy": "auth0",
                        "client_name": "Default App",
                        "user_agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0"
                    },
                    "log_id": "90020211103030725428115389447533113776256732300526485554"
                }
            },
            "log": {
                "level": "error"
            },
            "event": {
                "action": "invalid-username-or-email",
                "category": [
                    "authentication",
                    "threat"
                ],
                "type": [
                    "info",
                    "indicator"
                ],
                "kind": "event",
                "outcome": "failure"
            }
        },
        {
            "@timestamp": "2021-11-03T08:25:14.466Z",
            "ecs": {
                "version": "1.12.0"
            },
            "auth0": {
                "logs": {
                    "data": {
                        "date": "2021-11-03T08:25:14.466Z",
                        "log_id": "90020211103082515482106767167326018758436529088273317970",
                        "user_name": "new@test.com",
                        "ip": "114.76.60.57",
                        "description": "Wrong email or password.",
                        "strategy_type": "database",
                        "type": "Incorrect password",
                        "classification": "Login - Failure",
                        "client_id": "aI61p8I8aFjmYRliLWgvM9ev97kCCNDB",
                        "connection_id": "con_1a5wCUmAs6VOU17n",
                        "user_id": "auth0|61823277a44a21007221a59a",
                        "connection": "Username-Password-Authentication",
                        "details": {
                            "error": {
                                "message": "Wrong email or password."
                            }
                        },
                        "strategy": "auth0",
                        "client_name": "Default App",
                        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
                    },
                    "log_id": "90020211103082515482106767167326018758436529088273317970"
                }
            },
            "log": {
                "level": "error"
            },
            "event": {
                "action": "incorrect-password",
                "category": [
                    "authentication"
                ],
                "type": [
                    "info"
                ],
                "kind": "event",
                "outcome": "failure"
            }
        }
    ]
}